language: ruby
cache:
  - bundler
  - apt
before_install:
  - sudo add-apt-repository ppa:samrog131/ppa
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg
rvm:
  - 2.1.1
notifications:
  email:
    on_success: change
